// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/v1alpha1/calc.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type CalculateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tensors       []*Tensor `protobuf:"bytes,1,rep,name=tensors,proto3" json:"tensors,omitempty"`
	OutputTensors []int32   `protobuf:"varint,2,rep,packed,name=output_tensors,json=outputTensors,proto3" json:"output_tensors,omitempty"`
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetTensors() []*Tensor {
	if x != nil {
		return x.Tensors
	}
	return nil
}

func (x *CalculateRequest) GetOutputTensors() []int32 {
	if x != nil {
		return x.OutputTensors
	}
	return nil
}

// The response message containing the greetings
type CalculateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Tensor `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetResults() []*Tensor {
	if x != nil {
		return x.Results
	}
	return nil
}

type Tensor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source      *Source          `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	InlineData  *InlineData      `protobuf:"bytes,3,opt,name=inline_data,json=inlineData,proto3" json:"inline_data,omitempty"`
	Computation *TensorOperation `protobuf:"bytes,4,opt,name=computation,proto3" json:"computation,omitempty"`
}

func (x *Tensor) Reset() {
	*x = Tensor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tensor) ProtoMessage() {}

func (x *Tensor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tensor.ProtoReflect.Descriptor instead.
func (*Tensor) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{2}
}

func (x *Tensor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tensor) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Tensor) GetInlineData() *InlineData {
	if x != nil {
		return x.InlineData
	}
	return nil
}

func (x *Tensor) GetComputation() *TensorOperation {
	if x != nil {
		return x.Computation
	}
	return nil
}

type Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source) Reset() {
	*x = Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{3}
}

type InlineData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dimensions []int32   `protobuf:"varint,1,rep,packed,name=dimensions,proto3" json:"dimensions,omitempty"`
	Values     []float32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *InlineData) Reset() {
	*x = InlineData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InlineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineData) ProtoMessage() {}

func (x *InlineData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineData.ProtoReflect.Descriptor instead.
func (*InlineData) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{4}
}

func (x *InlineData) GetDimensions() []int32 {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *InlineData) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TensorOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//
	//	*TensorOperation_LinearScale
	//	*TensorOperation_RmsNorm
	//	*TensorOperation_DotMultiply
	//	*TensorOperation_Add
	//	*TensorOperation_Silu
	//	*TensorOperation_Softmax
	Operation isTensorOperation_Operation `protobuf_oneof:"operation"`
}

func (x *TensorOperation) Reset() {
	*x = TensorOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TensorOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorOperation) ProtoMessage() {}

func (x *TensorOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorOperation.ProtoReflect.Descriptor instead.
func (*TensorOperation) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{5}
}

func (m *TensorOperation) GetOperation() isTensorOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *TensorOperation) GetLinearScale() *LinearScale {
	if x, ok := x.GetOperation().(*TensorOperation_LinearScale); ok {
		return x.LinearScale
	}
	return nil
}

func (x *TensorOperation) GetRmsNorm() *RMSNorm {
	if x, ok := x.GetOperation().(*TensorOperation_RmsNorm); ok {
		return x.RmsNorm
	}
	return nil
}

func (x *TensorOperation) GetDotMultiply() *DotMultiply {
	if x, ok := x.GetOperation().(*TensorOperation_DotMultiply); ok {
		return x.DotMultiply
	}
	return nil
}

func (x *TensorOperation) GetAdd() *Add {
	if x, ok := x.GetOperation().(*TensorOperation_Add); ok {
		return x.Add
	}
	return nil
}

func (x *TensorOperation) GetSilu() *Silu {
	if x, ok := x.GetOperation().(*TensorOperation_Silu); ok {
		return x.Silu
	}
	return nil
}

func (x *TensorOperation) GetSoftmax() *Softmax {
	if x, ok := x.GetOperation().(*TensorOperation_Softmax); ok {
		return x.Softmax
	}
	return nil
}

type isTensorOperation_Operation interface {
	isTensorOperation_Operation()
}

type TensorOperation_LinearScale struct {
	LinearScale *LinearScale `protobuf:"bytes,1,opt,name=linear_scale,json=linearScale,proto3,oneof"`
}

type TensorOperation_RmsNorm struct {
	RmsNorm *RMSNorm `protobuf:"bytes,2,opt,name=rms_norm,json=rmsNorm,proto3,oneof"`
}

type TensorOperation_DotMultiply struct {
	DotMultiply *DotMultiply `protobuf:"bytes,3,opt,name=dot_multiply,json=dotMultiply,proto3,oneof"`
}

type TensorOperation_Add struct {
	Add *Add `protobuf:"bytes,5,opt,name=add,proto3,oneof"`
}

type TensorOperation_Silu struct {
	Silu *Silu `protobuf:"bytes,20,opt,name=silu,proto3,oneof"`
}

type TensorOperation_Softmax struct {
	Softmax *Softmax `protobuf:"bytes,21,opt,name=softmax,proto3,oneof"`
}

func (*TensorOperation_LinearScale) isTensorOperation_Operation() {}

func (*TensorOperation_RmsNorm) isTensorOperation_Operation() {}

func (*TensorOperation_DotMultiply) isTensorOperation_Operation() {}

func (*TensorOperation_Add) isTensorOperation_Operation() {}

func (*TensorOperation_Silu) isTensorOperation_Operation() {}

func (*TensorOperation_Softmax) isTensorOperation_Operation() {}

type LinearScale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source int32   `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Scale  float32 `protobuf:"fixed32,2,opt,name=scale,proto3" json:"scale,omitempty"`
}

func (x *LinearScale) Reset() {
	*x = LinearScale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearScale) ProtoMessage() {}

func (x *LinearScale) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearScale.ProtoReflect.Descriptor instead.
func (*LinearScale) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{6}
}

func (x *LinearScale) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *LinearScale) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type RMSNorm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source  int32   `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Epsilon float32 `protobuf:"fixed32,2,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
}

func (x *RMSNorm) Reset() {
	*x = RMSNorm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RMSNorm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMSNorm) ProtoMessage() {}

func (x *RMSNorm) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMSNorm.ProtoReflect.Descriptor instead.
func (*RMSNorm) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{7}
}

func (x *RMSNorm) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RMSNorm) GetEpsilon() float32 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

type DotMultiply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []int32 `protobuf:"varint,1,rep,packed,name=sources,proto3" json:"sources,omitempty"`
}

func (x *DotMultiply) Reset() {
	*x = DotMultiply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DotMultiply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DotMultiply) ProtoMessage() {}

func (x *DotMultiply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DotMultiply.ProtoReflect.Descriptor instead.
func (*DotMultiply) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{8}
}

func (x *DotMultiply) GetSources() []int32 {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Add struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []int32 `protobuf:"varint,1,rep,packed,name=sources,proto3" json:"sources,omitempty"`
}

func (x *Add) Reset() {
	*x = Add{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Add) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Add) ProtoMessage() {}

func (x *Add) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Add.ProtoReflect.Descriptor instead.
func (*Add) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{9}
}

func (x *Add) GetSources() []int32 {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Silu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source int32 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *Silu) Reset() {
	*x = Silu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Silu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Silu) ProtoMessage() {}

func (x *Silu) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Silu.ProtoReflect.Descriptor instead.
func (*Silu) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{10}
}

func (x *Silu) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

type Softmax struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source int32 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *Softmax) Reset() {
	*x = Softmax{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1alpha1_calc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Softmax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Softmax) ProtoMessage() {}

func (x *Softmax) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_calc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Softmax.ProtoReflect.Descriptor instead.
func (*Softmax) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_calc_proto_rawDescGZIP(), []int{11}
}

func (x *Softmax) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

var File_api_v1alpha1_calc_proto protoreflect.FileDescriptor

var file_api_v1alpha1_calc_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x22, 0x72, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x54, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x52, 0x07, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x54, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x73, 0x22, 0x4c, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x74,
	0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0xdd, 0x01, 0x0a, 0x06, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x74, 0x72,
	0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x69, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x48, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x08, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x44, 0x0a, 0x0a,
	0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a,
	0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x8c, 0x03, 0x0a, 0x0f, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0c, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72,
	0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x48, 0x00, 0x52, 0x0b, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x12,
	0x3b, 0x0a, 0x08, 0x72, 0x6d, 0x73, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x4d, 0x53, 0x4e, 0x6f, 0x72,
	0x6d, 0x48, 0x00, 0x52, 0x07, 0x72, 0x6d, 0x73, 0x4e, 0x6f, 0x72, 0x6d, 0x12, 0x47, 0x0a, 0x0c,
	0x64, 0x6f, 0x74, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x44, 0x6f, 0x74, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x74, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x48, 0x00,
	0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x69, 0x6c, 0x75, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x69, 0x6c, 0x75,
	0x48, 0x00, 0x52, 0x04, 0x73, 0x69, 0x6c, 0x75, 0x12, 0x3a, 0x0a, 0x07, 0x73, 0x6f, 0x66, 0x74,
	0x6d, 0x61, 0x78, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x74, 0x72,
	0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x53, 0x6f, 0x66, 0x74, 0x6d, 0x61, 0x78, 0x48, 0x00, 0x52, 0x07, 0x73, 0x6f, 0x66,
	0x74, 0x6d, 0x61, 0x78, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x3b, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x53, 0x63, 0x61, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x3b,
	0x0a, 0x07, 0x52, 0x4d, 0x53, 0x4e, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x70, 0x73, 0x69, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x65, 0x70, 0x73, 0x69, 0x6c, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x0b, 0x44,
	0x6f, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x04, 0x53, 0x69, 0x6c, 0x75, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x21, 0x0a, 0x07, 0x53, 0x6f, 0x66, 0x74, 0x6d, 0x61, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x32, 0x71, 0x0a, 0x0d, 0x42, 0x69, 0x67, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x60, 0x0a, 0x09, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73, 0x74, 0x69, 0x6e,
	0x73, 0x62, 0x2f, 0x6b, 0x6c, 0x6c, 0x61, 0x6d, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1alpha1_calc_proto_rawDescOnce sync.Once
	file_api_v1alpha1_calc_proto_rawDescData = file_api_v1alpha1_calc_proto_rawDesc
)

func file_api_v1alpha1_calc_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_calc_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_calc_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1alpha1_calc_proto_rawDescData)
	})
	return file_api_v1alpha1_calc_proto_rawDescData
}

var file_api_v1alpha1_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1alpha1_calc_proto_goTypes = []interface{}{
	(*CalculateRequest)(nil),  // 0: matrixserver.v1alpha1.CalculateRequest
	(*CalculateResponse)(nil), // 1: matrixserver.v1alpha1.CalculateResponse
	(*Tensor)(nil),            // 2: matrixserver.v1alpha1.Tensor
	(*Source)(nil),            // 3: matrixserver.v1alpha1.Source
	(*InlineData)(nil),        // 4: matrixserver.v1alpha1.InlineData
	(*TensorOperation)(nil),   // 5: matrixserver.v1alpha1.TensorOperation
	(*LinearScale)(nil),       // 6: matrixserver.v1alpha1.LinearScale
	(*RMSNorm)(nil),           // 7: matrixserver.v1alpha1.RMSNorm
	(*DotMultiply)(nil),       // 8: matrixserver.v1alpha1.DotMultiply
	(*Add)(nil),               // 9: matrixserver.v1alpha1.Add
	(*Silu)(nil),              // 10: matrixserver.v1alpha1.Silu
	(*Softmax)(nil),           // 11: matrixserver.v1alpha1.Softmax
}
var file_api_v1alpha1_calc_proto_depIdxs = []int32{
	2,  // 0: matrixserver.v1alpha1.CalculateRequest.tensors:type_name -> matrixserver.v1alpha1.Tensor
	2,  // 1: matrixserver.v1alpha1.CalculateResponse.results:type_name -> matrixserver.v1alpha1.Tensor
	3,  // 2: matrixserver.v1alpha1.Tensor.source:type_name -> matrixserver.v1alpha1.Source
	4,  // 3: matrixserver.v1alpha1.Tensor.inline_data:type_name -> matrixserver.v1alpha1.InlineData
	5,  // 4: matrixserver.v1alpha1.Tensor.computation:type_name -> matrixserver.v1alpha1.TensorOperation
	6,  // 5: matrixserver.v1alpha1.TensorOperation.linear_scale:type_name -> matrixserver.v1alpha1.LinearScale
	7,  // 6: matrixserver.v1alpha1.TensorOperation.rms_norm:type_name -> matrixserver.v1alpha1.RMSNorm
	8,  // 7: matrixserver.v1alpha1.TensorOperation.dot_multiply:type_name -> matrixserver.v1alpha1.DotMultiply
	9,  // 8: matrixserver.v1alpha1.TensorOperation.add:type_name -> matrixserver.v1alpha1.Add
	10, // 9: matrixserver.v1alpha1.TensorOperation.silu:type_name -> matrixserver.v1alpha1.Silu
	11, // 10: matrixserver.v1alpha1.TensorOperation.softmax:type_name -> matrixserver.v1alpha1.Softmax
	0,  // 11: matrixserver.v1alpha1.BigCalculator.Calculate:input_type -> matrixserver.v1alpha1.CalculateRequest
	1,  // 12: matrixserver.v1alpha1.BigCalculator.Calculate:output_type -> matrixserver.v1alpha1.CalculateResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_calc_proto_init() }
func file_api_v1alpha1_calc_proto_init() {
	if File_api_v1alpha1_calc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1alpha1_calc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tensor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InlineData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TensorOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearScale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RMSNorm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DotMultiply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Add); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Silu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1alpha1_calc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Softmax); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1alpha1_calc_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*TensorOperation_LinearScale)(nil),
		(*TensorOperation_RmsNorm)(nil),
		(*TensorOperation_DotMultiply)(nil),
		(*TensorOperation_Add)(nil),
		(*TensorOperation_Silu)(nil),
		(*TensorOperation_Softmax)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1alpha1_calc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_calc_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_calc_proto_depIdxs,
		MessageInfos:      file_api_v1alpha1_calc_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_calc_proto = out.File
	file_api_v1alpha1_calc_proto_rawDesc = nil
	file_api_v1alpha1_calc_proto_goTypes = nil
	file_api_v1alpha1_calc_proto_depIdxs = nil
}
