// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/v1alpha1/calc.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BigCalculatorClient is the client API for BigCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BigCalculatorClient interface {
	// Performs a one-off calculation
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
}

type bigCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewBigCalculatorClient(cc grpc.ClientConnInterface) BigCalculatorClient {
	return &bigCalculatorClient{cc}
}

func (c *bigCalculatorClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/matrixserver.v1alpha1.BigCalculator/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BigCalculatorServer is the server API for BigCalculator service.
// All implementations must embed UnimplementedBigCalculatorServer
// for forward compatibility
type BigCalculatorServer interface {
	// Performs a one-off calculation
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
	mustEmbedUnimplementedBigCalculatorServer()
}

// UnimplementedBigCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedBigCalculatorServer struct {
}

func (UnimplementedBigCalculatorServer) Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedBigCalculatorServer) mustEmbedUnimplementedBigCalculatorServer() {}

// UnsafeBigCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BigCalculatorServer will
// result in compilation errors.
type UnsafeBigCalculatorServer interface {
	mustEmbedUnimplementedBigCalculatorServer()
}

func RegisterBigCalculatorServer(s grpc.ServiceRegistrar, srv BigCalculatorServer) {
	s.RegisterService(&BigCalculator_ServiceDesc, srv)
}

func _BigCalculator_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigCalculatorServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matrixserver.v1alpha1.BigCalculator/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigCalculatorServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BigCalculator_ServiceDesc is the grpc.ServiceDesc for BigCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BigCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matrixserver.v1alpha1.BigCalculator",
	HandlerType: (*BigCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _BigCalculator_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1alpha1/calc.proto",
}
